spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.35.43:5433/bnosoft
    username: postgres
    password: postgres
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  application:
    name: Bnoboard
  jpa:
    properties:
      hibernate:
        default_schema: board2025
        format_sql: true
      org.hibernate.envers:
        audit_table_suffix: History # 이력 테이블 이름의 _AUD를 History로 변경
        revision_field_name: revisionId # 이력 테이블 REV 컬럼명
        revision_type_field_name: revisionType # 이력 테이블 REVTYPE 컬럼명
        store_data_at_delete: true # 삭제시 저장 여부, 기본은 false
    show-sql: 'true'
    hibernate:
      ddl-auto: none
server:
  tomcat:
    use-relative-redirects: 'true'
  servlet:
    context-path: /api/v1
springdoc:
  packages-to-scan: com.bno.board_back.controller

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

env:
  tsid:
    tz: Asia/Seoul
    nodeBit: 5

jwt:
  secret: fthl4TRfGF0sDwEUqhL/L5JZ/NEIfaTHdai7FD51FMN5

file:
  allowed:
    file_extension: txt,xlsx,png,jpg

minio:
  url: http://localhost:9000
  bucket:
    name: bnoboard
  access:
    key: ufShJ6zijnHjumMNh2og
    secret: bXEffSWJ1Lxr99SiUJdSlzSrkU3zsAxId9SEaTyf
